Description: WAF WebACL
Parameters:
    ProjectName:
      Type: String
    EnvName:
      Type: String
    WAFName:
      Type: String
    ALBARN:
      Type: String
Resources:
  IPSetWhitelist: 
    Type: AWS::WAFv2::IPSet
    Properties: 
      Addresses: 
        - 185.170.45.38/32
      IPAddressVersion: IPV4
      Name: lbc-prod-ip-set-whitelist
      Scope: REGIONAL
      Tags: 
        - Key: project
          Value: 
            Ref: ProjectName
        - Key: env
          Value: 
            Ref: EnvName
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: 
        Ref: WAFName
      Scope: REGIONAL
      Description: WAF WebACL
      Tags: 
        - Key: project
          Value: 
            Ref: ProjectName
        - Key: env
          Value: 
            Ref: EnvName
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: 
          Ref: WAFName
      Rules:
        - Name: lbc-prod-rule-ip-whitelist
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: lbc-prod-rule-ip-whitelist
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt IPSetWhitelist.Arn
        - Name: lbc-prod-rule-timeOne-allow
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: lbc-prod-rule-timeOne-allow
          Statement:
            ByteMatchStatement:
              FieldToMatch: 
                QueryString: Json
              PositionalConstraint: CONTAINS
              SearchString: 
                utm_source=TimeOne
              TextTransformations: 
                - Priority: 0
                  Type: None
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: SizeRestrictions_QUERYSTRING
                - Name: SizeRestrictions_BODY
                - Name: SizeRestrictions_URIPATH
                - Name: GenericRFI_QUERYARGUMENTS
                - Name: GenericRFI_BODY
        - Name: AWSManagedRulesAnonymousIpList
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAnonymousIpList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
              ExcludedRules:
                - Name: HostingProviderIPList
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAmazonIpReputationList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
              ExcludedRules: []
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 5
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules: []
        - Name: AWSManagedRulesPHPRuleSet
          Priority: 6
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesPHPRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesPHPRuleSet
              ExcludedRules: []
        - Name: AWSManagedRulesLinuxRuleSet
          Priority: 7
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesLinuxRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
              ExcludedRules: []
        - Name: AWSManagedRulesWordPressRuleSet
          Priority: 8
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesWordPressRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesWordPressRuleSet
              ExcludedRules: []
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: 
        Ref: ALBARN
      WebACLArn: !GetAtt WAFWebACL.Arn